### PR TITLE
Sb areas

### PR DESCRIPTION
**Pull request by sueboyd922**
__x__ Wrote Tests
__x__ Implemented
__x__ Reviewed

## Necessary checkmarks:
- [x] All Tests are Passing
- [x] The code will run locally

## Type of change
- [x] New feature
- [x] Bug Fix

## Implements/Fixes:
* Added Area table and model via migration
* Added rake file to load all areas into database run (`rake load_areas:areas`)
* JSON file full of climbing areas in DB folder
* Removed location attribute from trips
* Added foreign key area_id to trips
* Fixed all the tests after all of the above

## Check the correct boxes
- [x] This broke nothing ***
- [x] All Tests are Passing
- [x] The code will run locally

## Testing Changes
- [x] Tests have been added
- [] No Tests have been changed
- [] Some Tests have been changed
- [x] All of the Tests have been changed(Please describe what in the world happened) **DATABASE see above**

## Checklist:
- [] My code has no unused/commented out code
- [x] I have reviewed my code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code
- [x] I have removed any testing syntax (save_and_open_page/pry) in my spec files

### CODE REVIEW

**Comment by phillipkamps** [comment]
I'm taking partial credit for this monster of a PR

**Review by phillipkamps — APPROVED** [review]
great pair - this was a beast of a PR
GO TEAM!

**Comment by ShermanA-13** [comment]
It looks goood, whoooo!!!!

**Review by ShermanA-13 — COMMENTED** [review]
WHOOOOO!!!!

**Pull request merged**
